#CUDA_VISIBLE_DEVICES=0,1,2,3 python -m torch.distributed.launch --nproc_per_node=4 --use_env train.py -opt ./options/train/COSISR_x4_sim.yml --launcher pytorch
# general settings
name: COSISR_x4_sim
model_type: ODISRModel
scale: 4
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: ODISR_train
    type: ERPPairedImageDataset
    dataroot_gt: /COSISR/datasets/SIM-SR/train/HR_sub
    dataroot_lq: /COSISR/datasets/SIM-SR/train/LR_sub/X4_sub
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: false
    return_top: true
    force_resize: true
    gt_h: 480
    gt_w: 1696
    condition_type: X4
    sub_image: true
    
    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: ODISR_val
    type: ERPPairedImageDataset
    dataroot_gt:  /COSISR/datasets/SIM-SR/validation/HR
    dataroot_lq:  /COSISR/datasets/SIM-SR/validation/LR/X4
    io_backend:
      type: disk

    condition_type: X4

# network structures
network_g:
  type: COSISR
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  c_dim: 256
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  condition_dim: 2
  vit_condition: [6, 6, 6, 6, 6, 6]
  vit_condition_type: '3conv'
  window_condition: true
  dcn_condition: [1, 1, 1, 1, 1, 1, 1]
  dcn_condition_type: '2conv'

# path
path:
  pretrain_network_g: /COSISR/pretrained_models/COSISR_X4.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [80000]
    gamma: 0.5

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings (slurm only)
dist_params:
  backend: nccl
  port: 29500